version: '3'

services:
  canister:
    build: ./expose_metrics
    ports:
      - 8000:8000
    volumes:
      - prometheus-data:/prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
volumes:
  prometheus-data: