groups:
  - name: LowCycleAlert
    rules:
      - alert: LowCycles 
        expr: balance < 100000000
  - name: HeapAlmostFullAlert
    rules:
      - alert: HeapAt80Percent
        expr: heap_size > 48828
      - alert: HeapAt90Percent
        expr: heap_size > 54931
