global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'canister_metrics'
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - /prometheus/prometheus_target.json