global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    authorization:
      credentials: "MySecretKey"
    static_configs:
      - targets:
          - 'canister'